import argparse
import json
import os
import re


OUTPUT_NEWLINE = "\r\n"

GENERATED_AUTOGEN_HEADER = """-- Generated by tools/fgui_autogen/fairygui_autogen.py.
-- Do not put business logic in this file.

"""

GENERATED_SCAFFOLD_HEADER = """-- Generated scaffold by tools/fgui_autogen/fairygui_autogen.py.
-- Safe to edit. Re-run with --force preserves FairyGUIUserCode blocks.

"""

USER_CODE_PATTERN = re.compile(r"-- <FairyGUIUserCode:([^>\n]+)>\n(.*?)-- </FairyGUIUserCode:\1>", re.S)


def read_manifest(path):
	if not path:
		return {}
	with open(path, "r", encoding="utf-8") as file:
		return json.load(file)


def parse_control(value):
	parts = value.split(":")
	name = parts[0]
	path = parts[1] if len(parts) > 1 and parts[1] else name
	control_type = parts[2] if len(parts) > 2 and parts[2] else "GObject"
	return {
		"name": name,
		"path": path,
		"type": control_type,
	}


def sanitize_identifier(value):
	name = re.sub(r"[^0-9A-Za-z_]", "_", value or "")
	if not name:
		return "node"
	if name[0].isdigit():
		name = "_" + name
	return name


def to_camel_field(value):
	name = sanitize_identifier(value)
	parts = [part for part in name.split("_") if part]
	if not parts:
		return "node"
	field = parts[0]
	for part in parts[1:]:
		field += part[:1].upper() + part[1:]
	field = field[:1].lower() + field[1:]
	return sanitize_identifier(field)


def to_pascal_name(value):
	name = to_camel_field(value)
	return name[:1].upper() + name[1:]


def list_refresh_name(field_name):
	name = to_pascal_name(field_name)
	if name.endswith("List"):
		return "Refresh" + name
	return "Refresh" + name + "List"


def list_render_name(field_name):
	name = to_pascal_name(field_name)
	if name.endswith("List"):
		name = name[:-4]
	return "Render" + name + "Item"


def lua_bool(value):
	return "true" if value else "false"


def parse_bool(value):
	if value is None:
		return None
	value = str(value).lower()
	if value in ("1", "true", "yes", "on"):
		return True
	if value in ("0", "false", "no", "off"):
		return False
	raise argparse.ArgumentTypeError("expected true or false")


def get_field_name(control, field_style):
	name = control.get("name") or control.get("path") or "node"
	if field_style == "manifest":
		return sanitize_identifier(name)
	return to_camel_field(name)


def get_controls(manifest, control_args):
	controls = manifest.get("controls") or [parse_control(value) for value in control_args]
	return controls


def get_controllers(manifest):
	return manifest.get("controllers") or []


def get_transitions(manifest):
	return manifest.get("transitions") or []


def get_list_controls(controls):
	return [control for control in controls if control.get("type") == "GList" or control.get("xmlTag") == "list"]


def get_item_control_names(control, component_controls):
	component_name = control.get("defaultItemComponent")
	if not component_name:
		return []
	component_info = component_controls.get(component_name) or {}
	return [item.get("name") for item in component_info.get("controls") or [] if item.get("name")]


def get_item_control_defs(control, component_controls):
	component_name = control.get("defaultItemComponent")
	if not component_name:
		return []
	component_info = component_controls.get(component_name) or {}
	return [item for item in component_info.get("controls") or [] if item.get("name")]


def ensure_dir(path):
	if not os.path.isdir(path):
		os.makedirs(path)


def normalize_newlines(content):
	return content.replace("\r\n", "\n").replace("\r", "\n")


def to_output_newlines(content):
	return normalize_newlines(content).replace("\n", OUTPUT_NEWLINE)


def read_text_file(path):
	with open(path, "r", encoding="utf-8", newline="") as file:
		return file.read()


def write_text_file(path, content):
	with open(path, "w", encoding="utf-8", newline="") as file:
		file.write(to_output_newlines(content))


def write_file(path, content, force=False):
	if os.path.exists(path) and not force:
		return False
	write_text_file(path, content)
	return True


def user_code_key(ui_name, class_suffix, section):
	return "{0}{1}:{2}".format(ui_name, class_suffix, section)


def append_user_code_region(lines, ui_name, class_suffix, section, default_lines=None):
	key = user_code_key(ui_name, class_suffix, section)
	lines.append("-- <FairyGUIUserCode:{0}>".format(key))
	for line in default_lines or []:
		lines.append(line)
	lines.append("-- </FairyGUIUserCode:{0}>".format(key))


def extract_user_code_regions(content):
	content = normalize_newlines(content or "")
	return {matched.group(1): matched.group(2) for matched in USER_CODE_PATTERN.finditer(content)}


def has_user_code_regions(content):
	return bool(extract_user_code_regions(content))


def merge_user_code_regions(generated_content, existing_content):
	regions = extract_user_code_regions(existing_content)
	if not regions:
		return generated_content

	def replace_region(matched):
		key = matched.group(1)
		body = regions.get(key)
		if body is None:
			return matched.group(0)
		return "-- <FairyGUIUserCode:{0}>\n{1}-- </FairyGUIUserCode:{0}>".format(key, body)

	return USER_CODE_PATTERN.sub(replace_region, generated_content)


def class_file(output_dir, class_name):
	return os.path.join(output_dir, class_name + ".lua")


def lua_string(value):
	text = str(value or "")
	text = text.replace("\\", "\\\\").replace("\"", "\\\"").replace("\r", "\\r").replace("\n", "\\n")
	return '"' + text + '"'


def append_lua_string_map(lines, table_name, values):
	lines.append("{0}AutoGen.{1} = {{".format(table_name[0], table_name[1]))
	for key, value in values:
		lines.append("\t{0} = {1},".format(key, lua_string(value)))
	lines.append("}")
	lines.append("")


def append_lua_control_type_map(lines, ui_name, controls, field_style):
	lines.append("{0}AutoGen.ControlType = {{".format(ui_name))
	for control in controls:
		field_name = get_field_name(control, field_style)
		lines.append("\t{0} = {1},".format(field_name, lua_string(control.get("type") or "GObject")))
	lines.append("}")
	lines.append("")


def append_lua_list_item_map(lines, ui_name, controls, component_controls, field_style):
	lines.append("{0}AutoGen.ListItem = {{".format(ui_name))
	for control in get_list_controls(controls):
		field_name = get_field_name(control, field_style)
		lines.append("\t{0} = {{".format(field_name))
		lines.append("\t\tpath = {0},".format(lua_string(control.get("path"))))
		if control.get("defaultItemComponent"):
			lines.append("\t\tcomponent = {0},".format(lua_string(control.get("defaultItemComponent"))))
		if control.get("defaultItemResourceId"):
			lines.append("\t\tresourceId = {0},".format(lua_string(control.get("defaultItemResourceId"))))
		if control.get("selectionController"):
			lines.append("\t\tselectionController = {0},".format(lua_string(control.get("selectionController"))))
		item_controls = get_item_control_defs(control, component_controls)
		if item_controls:
			lines.append("\t\tcontrols = {")
			for item in item_controls:
				item_field = get_field_name(item, field_style)
				lines.append("\t\t\t{0} = {{ path = {1}, type = {2} }},".format(item_field, lua_string(item.get("path")), lua_string(item.get("type") or "GObject")))
			lines.append("\t\t},")
		lines.append("\t},")
	lines.append("}")
	lines.append("")


def render_autogen(ui_name, controls=None, controllers=None, transitions=None, component_controls=None, field_style="camel"):
	controls = controls or []
	controllers = controllers or []
	transitions = transitions or []
	component_controls = component_controls or {}
	lines = [
		GENERATED_AUTOGEN_HEADER.rstrip(),
		"",
		'local {0}AutoGen = Class("{0}AutoGen", ClassList.FairyGuiAutoGen)'.format(ui_name),
		"",
	]
	append_lua_string_map(lines, (ui_name, "ControlPath"), [(get_field_name(control, field_style), control.get("path")) for control in controls])
	append_lua_control_type_map(lines, ui_name, controls, field_style)
	append_lua_string_map(lines, (ui_name, "ControllerPath"), [(get_field_name(controller, field_style), controller.get("path")) for controller in controllers])
	append_lua_string_map(lines, (ui_name, "TransitionName"), [(get_field_name(transition, field_style), transition.get("path")) for transition in transitions])
	append_lua_list_item_map(lines, ui_name, controls, component_controls, field_style)
	lines.extend([
		"function {0}AutoGen:Create(param)".format(ui_name),
		"\treturn ClassList.{0}AutoGen.new(param)".format(ui_name),
		"end",
		"",
		"function {0}AutoGen:GetControlPath(name)".format(ui_name),
		"\treturn {0}AutoGen.ControlPath[name]".format(ui_name),
		"end",
		"",
		"function {0}AutoGen:GetControlType(name)".format(ui_name),
		"\treturn {0}AutoGen.ControlType[name]".format(ui_name),
		"end",
		"",
		"function {0}AutoGen:GetControllerPath(name)".format(ui_name),
		"\treturn {0}AutoGen.ControllerPath[name]".format(ui_name),
		"end",
		"",
		"function {0}AutoGen:GetTransitionName(name)".format(ui_name),
		"\treturn {0}AutoGen.TransitionName[name]".format(ui_name),
		"end",
		"",
		"function {0}AutoGen:GetListItemDefine(name)".format(ui_name),
		"\treturn {0}AutoGen.ListItem[name]".format(ui_name),
		"end",
		"",
		"return {0}AutoGen".format(ui_name),
		"",
	])
	return "\n".join(lines)


def render_view(ui_name, controls, controllers, field_style):
	lines = [
		GENERATED_SCAFFOLD_HEADER.rstrip(),
		"",
		'local {0}View = Class("{0}View", ClassList.FairyGuiBaseMvcView)'.format(ui_name),
		"",
	]
	append_user_code_region(lines, ui_name, "View", "locals")
	lines.extend([
		"",
		"function {0}View:Create(param)".format(ui_name),
		"\treturn ClassList.{0}View.new(param)".format(ui_name),
		"end",
		"",
		"function {0}View:GetHandleNodes()".format(ui_name),
		"\tself.widgets.root = self:GetRootHandle()",
	])
	for controller in controllers:
		field_name = get_field_name(controller, field_style)
		lines.append('\tself.widgets.{0} = "{1}"'.format(field_name, controller["path"]))
	for control in controls:
		field_name = get_field_name(control, field_style)
		lines.append('\tself.widgets.{0} = self:GetChild("{1}")'.format(field_name, control["path"]))
	lines.append("")
	append_user_code_region(lines, ui_name, "View", "GetHandleNodes", ["\t-- Add custom widget aliases here."])
	lines.extend([
		"\treturn self.widgets",
		"end",
		"",
		"function {0}View:InitView()".format(ui_name),
	])
	append_user_code_region(lines, ui_name, "View", "InitView", ["\t-- Add custom view initialization here."])
	lines.extend([
		"end",
		"",
	])
	append_user_code_region(lines, ui_name, "View", "custom")
	lines.extend([
		"",
		"return {0}View".format(ui_name),
		"",
	])
	return "\n".join(lines)


def render_model(ui_name):
	lines = [
		GENERATED_SCAFFOLD_HEADER.rstrip(),
		"",
		'local {0}Model = Class("{0}Model", ClassList.FairyGuiBaseModel)'.format(ui_name),
		"",
	]
	append_user_code_region(lines, ui_name, "Model", "locals")
	lines.extend([
		"",
		"function {0}Model:Create(param)".format(ui_name),
		"\treturn ClassList.{0}Model.new(param)".format(ui_name),
		"end",
		"",
		"function {0}Model:Init(param)".format(ui_name),
		"\tClassList.FairyGuiBaseModel.Init(self, param)",
	])
	append_user_code_region(lines, ui_name, "Model", "Init", ["\t-- Initialize model data here."])
	lines.extend([
		"end",
		"",
	])
	append_user_code_region(lines, ui_name, "Model", "custom")
	lines.extend([
		"",
		"return {0}Model".format(ui_name),
		"",
	])
	return "\n".join(lines)


def render_ctrl(ui_name, controls, component_controls, field_style):
	lines = [
		GENERATED_SCAFFOLD_HEADER.rstrip(),
		"",
		'local {0}Ctrl = Class("{0}Ctrl", ClassList.FairyGuiBaseCtrl)'.format(ui_name),
		"",
	]
	append_user_code_region(lines, ui_name, "Ctrl", "locals")
	lines.extend([
		"",
		"function {0}Ctrl:Create(param)".format(ui_name),
		"\treturn ClassList.{0}Ctrl.new(param)".format(ui_name),
		"end",
		"",
		"function {0}Ctrl:RegisterUIEvents()".format(ui_name),
	])
	append_user_code_region(lines, ui_name, "Ctrl", "RegisterUIEvents", ["\t-- Register custom UI events here."])
	lines.extend([
		"end",
		"",
		"function {0}Ctrl:Refresh()".format(ui_name),
	])
	list_controls = get_list_controls(controls)
	for control in list_controls:
		field_name = get_field_name(control, field_style)
		lines.append('\tself:{0}()'.format(list_refresh_name(field_name)))
	lines.append("")
	append_user_code_region(lines, ui_name, "Ctrl", "Refresh", ["\t-- Refresh custom state here."])
	lines.extend([
		"end",
		"",
	])

	for control in list_controls:
		field_name = get_field_name(control, field_style)
		refresh_method = list_refresh_name(field_name)
		render_method = list_render_name(field_name)
		path = control["path"]
		data_key = field_name + "Data"
		lines.extend([
			"function {0}Ctrl:{1}()".format(ui_name, refresh_method),
			'\tlocal dataList = self.model ~= nil and self.model:GetByKey("{0}") or nil'.format(data_key),
			"\tdataList = dataList or {}",
			'\treturn self:SetListData("{0}", dataList, function(item, data, index)'.format(path),
			"\t\tself:{0}(item, data, index)".format(render_method),
			"\tend)",
			"end",
			"",
		])
		item_component = control.get("defaultItemComponent")
		item_control_names = get_item_control_names(control, component_controls)
		if item_component:
			lines.append("-- item component: {0}".format(item_component))
		if item_control_names:
			lines.append("-- item controls: {0}".format(", ".join(item_control_names)))
		lines.extend([
			"function {0}Ctrl:{1}(item, data, index)".format(ui_name, render_method),
		])
		append_user_code_region(lines, ui_name, "Ctrl", render_method, ["\t-- Render item data here."])
		lines.extend([
			"end",
			"",
		])

	append_user_code_region(lines, ui_name, "Ctrl", "custom")
	lines.extend([
		"",
		"return {0}Ctrl".format(ui_name),
		"",
	])
	return "\n".join(lines)


def render_registry_entry(ui_name, package_name, component_name, module_prefix, args):
	lines = [
	"\t{0} = {{".format(ui_name),
	'\t\tpackage = "{0}",'.format(package_name),
	'\t\tcomponent = "{0}",'.format(component_name),
	'\t\tclasslua = "{0}AutoGen",'.format(ui_name),
	'\t\tlayer = "{0}",'.format(args.layer),
	'\t\tgroup = "{0}",'.format(args.group),
	'\t\tscene = "{0}",'.format(args.scene),
	"\t\tcache = {0},".format(lua_bool(args.cache)),
	]
	if args.full_screen:
		lines.append("\t\tfullScreen = true,")
	if args.modal:
		lines.append("\t\tmodal = true,")
		lines.append("\t\tmodalAlpha = {0},".format(args.modal_alpha))
	if args.close_on_mask_click:
		lines.append("\t\tcloseOnMaskClick = true,")
	if args.close_on_escape:
		lines.append("\t\tcloseOnEscape = true,")
	if args.popup_mode:
		lines.append('\t\tpopupMode = "{0}",'.format(args.popup_mode))
	lines.extend([
	"\t\trequires = {",
	'\t\t\t"{0}.{1}Ctrl",'.format(module_prefix, ui_name),
	'\t\t\t"{0}.{1}Model",'.format(module_prefix, ui_name),
	'\t\t\t"{0}.{1}View",'.format(module_prefix, ui_name),
	'\t\t\t"{0}.{1}AutoGen",'.format(module_prefix, ui_name),
	"\t\t},",
	"\t},",
	])
	return "\n".join(lines)


def render_registry(ui_name, package_name, component_name, module_prefix, args):
	return """-- Generated by tools/fgui_autogen/fairygui_autogen.py.

return {{
{0}
}}
""".format(render_registry_entry(ui_name, package_name, component_name, module_prefix, args))


def render_aggregate_registry(ui_name, entry):
	return """-- Generated by tools/fgui_autogen/fairygui_autogen.py.
-- Hand-written UIRegistry.lua entries take priority at runtime.

local GeneratedUIRegistry = {{
-- <FairyGUIAutoGen:{0}>
{1}
-- </FairyGUIAutoGen:{0}>
}}

return GeneratedUIRegistry
""".format(ui_name, entry)


def render_updated_aggregate_registry(content, ui_name, entry):
	start_marker = "-- <FairyGUIAutoGen:{0}>".format(ui_name)
	end_marker = "-- </FairyGUIAutoGen:{0}>".format(ui_name)
	block = "{0}\n{1}\n{2}".format(start_marker, entry, end_marker)

	if content is None:
		return render_aggregate_registry(ui_name, entry)

	content = normalize_newlines(content)
	start = content.find(start_marker)
	end = content.find(end_marker)
	if start >= 0 and end >= start:
		end += len(end_marker)
		content = content[:start] + block + content[end:]
	else:
		insert_at = content.rfind("\n}\n\nreturn GeneratedUIRegistry")
		if insert_at < 0:
			content = render_aggregate_registry(ui_name, entry)
		else:
			content = content[:insert_at] + "\n" + block + content[insert_at:]

	return content


def update_aggregate_registry(path, ui_name, entry):
	content = read_text_file(path) if os.path.exists(path) else None
	updated = render_updated_aggregate_registry(content, ui_name, entry)
	if content is not None and content == to_output_newlines(updated):
		return False

	write_text_file(path, updated)
	return True


def write_registry(path, registry, force=False):
	if not path:
		return False
	return write_file(path, registry, force=force)


def main():
	parser = argparse.ArgumentParser(description="Generate FairyGUI Lua MVC stubs.")
	parser.add_argument("--manifest", help="JSON manifest generated by tooling or written manually.")
	parser.add_argument("--ui-name", help="UI class prefix, for example Act37TestMvc.")
	parser.add_argument("--package", dest="package_name", help="FairyGUI package name.")
	parser.add_argument("--component", help="FairyGUI component name.")
	parser.add_argument("--module-prefix", default="res.scripts.ui.views")
	parser.add_argument("--output-dir", default=os.path.join("bin", "res", "scripts", "ui", "views"))
	parser.add_argument("--registry-output", help="Write a standalone registry Lua table for review or manual merge.")
	parser.add_argument("--registry-aggregate-output", help="Update a generated registry module with this UI entry.")
	parser.add_argument("--control", action="append", default=[], help="Control spec: fieldName[:childPath[:type]].")
	parser.add_argument("--field-style", choices=("camel", "manifest"), default="camel")
	parser.add_argument("--layer", default="Normal")
	parser.add_argument("--group", default="")
	parser.add_argument("--scene", default="Default")
	parser.add_argument("--cache", type=parse_bool, default=True)
	parser.add_argument("--full-screen", action="store_true")
	parser.add_argument("--modal", action="store_true")
	parser.add_argument("--modal-alpha", default="0.35")
	parser.add_argument("--close-on-mask-click", action="store_true")
	parser.add_argument("--close-on-escape", action="store_true")
	parser.add_argument("--popup-mode")
	parser.add_argument("--force", action="store_true", help="Refresh existing files; View / Model / Ctrl FairyGUIUserCode blocks are preserved.")
	args = parser.parse_args()

	manifest = read_manifest(args.manifest)
	ui_name = args.ui_name or manifest.get("uiName")
	package_name = args.package_name or manifest.get("package")
	component = args.component or manifest.get("component") or ui_name
	controls = get_controls(manifest, args.control)
	controllers = get_controllers(manifest)
	transitions = get_transitions(manifest)
	component_controls = manifest.get("componentControls") or {}

	if not ui_name or not package_name:
		raise SystemExit("--ui-name and --package are required when manifest does not provide them")

	ensure_dir(args.output_dir)
	written = []
	for class_name, content, overwrite, preserve_user_code in [
		(ui_name + "AutoGen", render_autogen(ui_name, controls, controllers, transitions, component_controls, args.field_style), True, False),
		(ui_name + "View", render_view(ui_name, controls, controllers, args.field_style), args.force, True),
		(ui_name + "Model", render_model(ui_name), args.force, True),
		(ui_name + "Ctrl", render_ctrl(ui_name, controls, component_controls, args.field_style), args.force, True),
	]:
		path = class_file(args.output_dir, class_name)
		if preserve_user_code and overwrite and os.path.exists(path):
			content = merge_user_code_regions(content, read_text_file(path))
		if write_file(path, content, force=overwrite):
			written.append(path)

	registry_entry = render_registry_entry(ui_name, package_name, component, args.module_prefix, args)
	registry = render_registry(ui_name, package_name, component, args.module_prefix, args)
	if args.registry_output:
		registry_dir = os.path.dirname(args.registry_output)
		if registry_dir:
			ensure_dir(registry_dir)
		if write_registry(args.registry_output, registry, force=True):
			written.append(args.registry_output)
	if args.registry_aggregate_output:
		registry_dir = os.path.dirname(args.registry_aggregate_output)
		if registry_dir:
			ensure_dir(registry_dir)
		if update_aggregate_registry(args.registry_aggregate_output, ui_name, registry_entry):
			written.append(args.registry_aggregate_output)

	print("Generated files:")
	for path in written:
		print("  " + path)
	print("")
	print("Registry entry:")
	print(registry_entry)


if __name__ == "__main__":
	main()
