#ifndef __AGENT_COMMAND_TYPES__
#define __AGENT_COMMAND_TYPES__

enum AgentCommandType
{
	AGENT_COMMAND_NONE = 0,
	AGENT_COMMAND_IDLE,
	AGENT_COMMAND_MOVE,
	AGENT_COMMAND_SHOOT,
	AGENT_COMMAND_DIE,
	AGENT_COMMAND_CHANGE_STANCE
};

#endif  // __AGENT_COMMAND_TYPES__
