#ifndef __AGENT_COMMAND_TYPES__
#define __AGENT_COMMAND_TYPES__

enum AgentCommandType
{
	AGENT_COMMAND_NONE = 0,
	AGENT_COMMAND_IDLE,
	AGENT_COMMAND_MOVE,
	AGENT_COMMAND_SHOOT,
	AGENT_COMMAND_DIE,
	AGENT_COMMAND_CHANGE_STANCE,
	AGENT_COMMAND_FALLING,          // internal override command
	AGENT_COMMAND_RELOAD,
	AGENT_COMMAND_WEAPON_TO_SMG,
	AGENT_COMMAND_WEAPON_TO_SNIPER
};

#endif  // __AGENT_COMMAND_TYPES__
