#ifndef __SOLDIER_OBJ_DEF__
#define __SOLDIER_OBJ_DEF__

//tolua_begin
#define SOLDIER_STAND_SPEED		3.0f
#define SOLDIER_STAND_HEIGHT	1.6f
#define SOLDIER_CROUCH_SPEED	1.0f
#define SOLDIER_CROUCH_HEIGHT	1.3f

enum SOLDIER_STATE 
{
    SSTATE_DEAD,
    SSTATE_FIRE,
    SSTATE_IDLE_AIM,
    SSTATE_RUN_FORWARD,
    SSTATE_RUN_BACKWARD,
    SSTATE_DEAD_HEADSHOT,
    SSTATE_FALL_DEAD,
    SSTATE_FALL_IDLE,
    SSTATE_JUMP_LAND,
    SSTATE_JUMP_UP,
    SSTATE_MELEE,
    SSTATE_RELOAD,
    SSTATE_SMG_TRANSFORM,
    SSTATE_SNIPER_TRANSFORM,

    // 不可直接使用
    CROUCH_SSTATE_DEAD,
    CROUCH_SSTATE_FIRE,
    CROUCH_SSTATE_IDLE_AIM,
    CROUCH_SSTATE_FORWARD,

    SSTATE_MAXCOUNT, // 标记位
};
//tolua_end

#endif  // __SOLDIER_OBJ_DEF__
